// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (gmail, password, update_at)
VALUES ($1, $2, $3)
RETURNING id, gmail
`

type CreateUserParams struct {
	Gmail    string
	Password string
	UpdateAt time.Time
}

type CreateUserRow struct {
	ID    uuid.UUID
	Gmail string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Gmail, arg.Password, arg.UpdateAt)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Gmail)
	return i, err
}
